import { createContext, useContext, useState, useRef, Dispatch, SetStateAction } from "react";
import { inputOption } from '@/app/page';
import {
  getOwnedIngredients,
  getAllIngredients,
} from "@/lib/services/Ingredients";

import { getRecommendedMeals, MealFilters } from '@/lib/services/Meal';

/**
 * supported dish type filters for recipe suggestions
 */
export type DishType = "" | "soup" | "stir-fried";

/**
 * supported nutrient priority filters for recipe suggestions
 */
export type NutrientPriority = "" | "muscle" | "bone" | "sick";

interface DashboardContextProps {
  /**
   * list of available ingredients for all users
   */
  ingredients: Ingredient[];
  setIngredients: (ingredients: Ingredient[]) => void;

  /**
   * list of ingredients owned by logged user
   */
  ownedIngredients: OwnedIngredient[];
  setOwnedIngredients: (ownedIngredients: OwnedIngredient[]) => void;

  /**
   * state for loading the owned ingredients
   */
  isLoadingOwnedIngredients: boolean;
  setIsLoadingOwnedIngredients: (isLoadingOwnedIngredients: boolean) => void;

  /**
   * selected ingredient from UI to add to inventory
   */
  selectedIngredientId: string;
  setSelectedIngredientId: (selectedIngredientId: string) => void;

  /**
   * suggestion dialog for displaying recipe suggestions from AI
   */
  suggestionDialogRef: React.RefObject<HTMLDialogElement | null>;

  /**
   * list of suggested recipes generated by AI
   */
  suggestedRecipes: Recipe[];
  setSuggestedRecipes: React.Dispatch<React.SetStateAction<Recipe[]>>;

  /**
   * state for loading suggestion from AI
   */
  isLoadingResponse: boolean;
  setIsLoadingResponse: (isLoadingResponse: boolean) => void;

  /**
   * active dish type filter applied when generating recipe suggestions
   */
  dishType: DishType;
  setDishType: (dishType: DishType) => void;

  /**
   * active nutrient priority filter applied when generating recipe suggestions
   */
  nutrientPriority: NutrientPriority;
  setNutrientPriority: (nutrientPriority: NutrientPriority) => void;

  /**
   * whether the AI may suggest ingredients beyond the user's inventory when generating recipe suggestions
   */
  allowSuggestedIngredients: boolean;
  setAllowSuggestedIngredients: (allowSuggestedIngredients: boolean) => void;

  /**
   * refresh the content of suggestion dialog
   */
  refreshRecommendedRecipes: () => Promise<void>;

  /**
   * fetch the owned ingredients by the user
   */
  fetchOwnedIngredients: () => Promise<void>;

  /**
   * resets the list of available ingredients for all users
   */
  RefreshIngredientList: () => Promise<void>;

  /**
   * state for loading while adding an ingredient
   */
  isLoadingAddIngredient: boolean;
  setIsLoadingAddIngredient: (isLoadingAddIngredient: boolean) => void;

  /**
   * state for temporarily saving the ingredients selected by the user
   */
  ingredientsToAdd: inputOption[];
  setIngredientsToAdd: Dispatch<SetStateAction<inputOption[]>>;

  /**
   * handles multiple selected Owned ingredients
   */
  selectedOwnedIngredientId: string[];
  setSelectedOwnedIngredientId: Dispatch<SetStateAction<string[]>>;

  isDeletingOwnedIngredients: boolean;
  setIsDeletingOwnedIngredients: Dispatch<SetStateAction<boolean>>;
}

export const DashboardContext = createContext<DashboardContextProps | undefined>(undefined!);

export function DashboardProvider({children}:{
  children: React.ReactNode
}){

  // state of available ingredients in the database
  const [ingredients, setIngredients] = useState<Ingredient[]>([]);
  // state of the ingredients retrieved from logged user's database
  const [ownedIngredients, setOwnedIngredients] = useState<OwnedIngredient[]>([]);

  // state for loading the owned ingredients
  const [isLoadingOwnedIngredients, setIsLoadingOwnedIngredients] = useState(false);

  // selected ingredient from UI to add to inventory
  const [selectedIngredientId, setSelectedIngredientId] = useState<string>("");

  // suggestion dialog
  const suggestionDialogRef = useRef<HTMLDialogElement | null>(null);

  // state for recipe suggestions
  const [suggestedRecipes, setSuggestedRecipes] = useState<Recipe[]>([]);

  // state for loading suggestion from AI
  const [isLoadingResponse, setIsLoadingResponse] = useState(false);

  // active dish type filter for recipe suggestions ("" = no filter)
  const [dishType, setDishType] = useState<DishType>("");

  // mirrors dishType so in-flight suggestion requests can detect filter changes
  const dishTypeRef = useRef<DishType>("");

  // active nutrient priority filter for recipe suggestions ("" = no priority)
  const [nutrientPriority, setNutrientPriority] = useState<NutrientPriority>("");

  // mirrors nutrientPriority so in-flight suggestion requests can detect filter changes
  const nutrientPriorityRef = useRef<NutrientPriority>("");

  // allow-suggested-ingredients flag for recipe suggestions (false = inventory only)
  const [allowSuggestedIngredients, setAllowSuggestedIngredients] = useState<boolean>(false);

  // mirrors allowSuggestedIngredients so in-flight suggestion requests can detect filter changes
  const allowSuggestedIngredientsRef = useRef<boolean>(false);

  // id of the most recent suggestion request; older requests are stale
  const latestRequestIdRef = useRef(0);

  /**
   * update the dish type filter and invalidate any in-flight suggestion request
   */
  function updateDishType(value: DishType){
    if (value === dishTypeRef.current){
      setDishType(value);
      return;
    }

    dishTypeRef.current = value;
    setDishType(value);

    invalidateInFlightSuggestions();
  }

  /**
   * update the nutrient priority filter and invalidate any in-flight suggestion request
   */
  function updateNutrientPriority(value: NutrientPriority){
    if (value === nutrientPriorityRef.current){
      setNutrientPriority(value);
      return;
    }

    nutrientPriorityRef.current = value;
    setNutrientPriority(value);

    invalidateInFlightSuggestions();
  }

  /**
   * update the allow-suggested-ingredients flag and invalidate any in-flight suggestion request
   */
  function updateAllowSuggestedIngredients(value: boolean){
    if (value === allowSuggestedIngredientsRef.current){
      setAllowSuggestedIngredients(value);
      return;
    }

    allowSuggestedIngredientsRef.current = value;
    setAllowSuggestedIngredients(value);

    invalidateInFlightSuggestions();
  }

  /**
   * invalidate any in-flight suggestion request for the old filters
   */
  function invalidateInFlightSuggestions(){
    latestRequestIdRef.current++;

    // no replacement request is running yet; stop the spinner here so a
    // discarded response cannot leave the dialog "thinking" forever
    setIsLoadingResponse(false);
  }

  // state for loading while adding an ingredient
  const [isLoadingAddIngredient, setIsLoadingAddIngredient] = useState(false);

  // state to temporarily store ingredients that the user wants to add
  const [ ingredientsToAdd, setIngredientsToAdd ] = useState<inputOption[]>([]);

  // selected id of the owned ingredients, can be used to delete/edit multiple ingredients at the same time
  const [ selectedOwnedIngredientId, setSelectedOwnedIngredientId ] = useState<string[]>([]);

  // state to check if owned ingredients are currently being deleted
  const [ isDeletingOwnedIngredients, setIsDeletingOwnedIngredients ] = useState(false);


  /**
   * reload the state for suggested recipes
   */
  async function refreshRecommendedRecipes(){
    // mark any prior in-flight request as superseded
    const requestId = ++latestRequestIdRef.current;

    try {
      setIsLoadingResponse(true);

      const requestedDishType = dishTypeRef.current;
      const requestedPriority = nutrientPriorityRef.current;
      const requestedAllowSuggested = allowSuggestedIngredientsRef.current;

      const filters: MealFilters = {};
      if (requestedDishType) filters.type = requestedDishType;
      if (requestedPriority) filters.nutrientPriority = requestedPriority;
      if (requestedAllowSuggested) filters.allowSuggestedIngredients = true;
      const hasFilters = Boolean(requestedDishType || requestedPriority || requestedAllowSuggested);

      const data = await getRecommendedMeals(hasFilters ? filters : undefined);

      // a newer request is in flight; let it own the result and the loading state
      if (requestId !== latestRequestIdRef.current) return;
      // a filter changed while this request was pending; discard the stale result
      if (requestedDishType !== dishTypeRef.current) return;
      if (requestedPriority !== nutrientPriorityRef.current) return;
      if (requestedAllowSuggested !== allowSuggestedIngredientsRef.current) return;

      setSuggestedRecipes(data!);
    } catch (error) {
      console.error(error);
    } finally {
      // keep the spinner running while a newer request is still pending
      if (requestId === latestRequestIdRef.current)
        setIsLoadingResponse(false);
    }
  } 

  /**
   * fetch the owned ingredients of logged user
   */
  async function fetchOwnedIngredients(){
    try {
      // update state for UI loading animation
      setIsLoadingOwnedIngredients(true);

      // fetch the owned ingredients
      const data = await getOwnedIngredients();
      setOwnedIngredients(data);
    } catch (error){
      console.error(error);
    } finally {
      setIsLoadingOwnedIngredients(false);
    }
  }
 
  /**
   * refresh the list of available ingredients
   */
  async function RefreshIngredientList(){
    const data = await getAllIngredients();
    setIngredients(data);
  }
  
  return (
    <DashboardContext.Provider value={{
      ingredients,
      setIngredients,
      ownedIngredients,
      setOwnedIngredients,
      isLoadingOwnedIngredients,
      setIsLoadingOwnedIngredients,
      selectedIngredientId,
      setSelectedIngredientId,
      suggestionDialogRef,
      suggestedRecipes,
      setSuggestedRecipes,
      isLoadingResponse,
      setIsLoadingResponse,
      dishType,
      setDishType: updateDishType,
      nutrientPriority,
      setNutrientPriority: updateNutrientPriority,
      allowSuggestedIngredients,
      setAllowSuggestedIngredients: updateAllowSuggestedIngredients,
      refreshRecommendedRecipes,
      fetchOwnedIngredients,
      RefreshIngredientList,
      isLoadingAddIngredient,
      setIsLoadingAddIngredient,
      ingredientsToAdd,
      setIngredientsToAdd,
      selectedOwnedIngredientId,
      setSelectedOwnedIngredientId,
      isDeletingOwnedIngredients,
      setIsDeletingOwnedIngredients
    }}>
      {children}
    </DashboardContext.Provider>
  );
}

export const useDashboardContext = () => useContext(DashboardContext);
