import { createContext, useContext, useState, useRef, useEffect, Dispatch, SetStateAction } from "react";
import { inputOption } from '@/app/page';
import {
  getOwnedIngredients,
  getAllIngredients,
} from "@/lib/services/Ingredients";

import { getRecommendedMeals, MealFilters } from '@/lib/services/Meal';
import { getPresets, savePreset, deletePreset } from '@/lib/services/Presets';

/**
 * supported dish type filters for recipe suggestions
 */
export type DishType = "" | "soup" | "stir-fried";

/**
 * supported nutrient priority filters for recipe suggestions
 */
export type NutrientPriority = "" | "muscle" | "bone" | "sick";

interface DashboardContextProps {
  /**
   * list of available ingredients for all users
   */
  ingredients: Ingredient[];
  setIngredients: (ingredients: Ingredient[]) => void;

  /**
   * list of ingredients owned by logged user
   */
  ownedIngredients: OwnedIngredient[];
  setOwnedIngredients: Dispatch<SetStateAction<OwnedIngredient[]>>;

  /**
   * state for loading the owned ingredients
   */
  isLoadingOwnedIngredients: boolean;
  setIsLoadingOwnedIngredients: (isLoadingOwnedIngredients: boolean) => void;

  /**
   * selected ingredient from UI to add to inventory
   */
  selectedIngredientId: string;
  setSelectedIngredientId: (selectedIngredientId: string) => void;

  /**
   * suggestion dialog for displaying recipe suggestions from AI
   */
  suggestionDialogRef: React.RefObject<HTMLDialogElement | null>;

  /**
   * list of suggested recipes generated by AI
   */
  suggestedRecipes: Recipe[];
  setSuggestedRecipes: React.Dispatch<React.SetStateAction<Recipe[]>>;

  /**
   * state for loading suggestion from AI
   */
  isLoadingResponse: boolean;
  setIsLoadingResponse: (isLoadingResponse: boolean) => void;

  /**
   * active dish type filter applied when generating recipe suggestions
   */
  dishType: DishType;
  setDishType: (dishType: DishType) => void;

  /**
   * active nutrient priority filter applied when generating recipe suggestions
   */
  nutrientPriority: NutrientPriority;
  setNutrientPriority: (nutrientPriority: NutrientPriority) => void;

  /**
   * whether the AI may suggest ingredients beyond the user's inventory when generating recipe suggestions
   */
  allowSuggestedIngredients: boolean;
  setAllowSuggestedIngredients: (allowSuggestedIngredients: boolean) => void;

  /**
   * market mode: when enabled, suggestions regenerate live (debounced) as the
   * user queues ingredients, considering the queued items alongside inventory
   */
  marketMode: boolean;
  setMarketMode: (marketMode: boolean) => void;

  /**
   * refresh the content of suggestion dialog
   */
  refreshRecommendedRecipes: () => Promise<void>;

  /**
   * instantly generate a single recipe suggestion (respecting active filters)
   * and return it so the caller can hand it off to the /recipe page
   */
  generateRecipeNow: () => Promise<Recipe | null>;

  /**
   * state for loading while instantly generating a recipe
   */
  isGeneratingNow: boolean;
  setIsGeneratingNow: (isGeneratingNow: boolean) => void;

  /**
   * fetch the owned ingredients by the user
   */
  fetchOwnedIngredients: () => Promise<void>;

  /**
   * resets the list of available ingredients for all users
   */
  RefreshIngredientList: () => Promise<void>;

  /**
   * state for loading while adding an ingredient
   */
  isLoadingAddIngredient: boolean;
  setIsLoadingAddIngredient: (isLoadingAddIngredient: boolean) => void;

  /**
   * state for temporarily saving the ingredients selected by the user
   */
  ingredientsToAdd: inputOption[];
  setIngredientsToAdd: Dispatch<SetStateAction<inputOption[]>>;

  /**
   * handles multiple selected Owned ingredients
   */
  selectedOwnedIngredientId: string[];
  setSelectedOwnedIngredientId: Dispatch<SetStateAction<string[]>>;

  isDeletingOwnedIngredients: boolean;
  setIsDeletingOwnedIngredients: Dispatch<SetStateAction<boolean>>;

  /**
   * list of saved fridge presets
   */
  presets: Preset[];
  setPresets: Dispatch<SetStateAction<Preset[]>>;

  /**
   * loading state for fetching presets
   */
  isLoadingPresets: boolean;
  setIsLoadingPresets: (isLoadingPresets: boolean) => void;

  /**
   * fetch the user's saved presets from the API
   */
  fetchPresets: () => Promise<void>;

  /**
   * save the user's current owned ingredients as a named preset
   */
  addPreset: (name: string) => Promise<void>;

  /**
   * populate ingredientsToAdd with a preset's ingredients
   */
  applyPreset: (preset: Preset) => void;

  /**
   * delete a preset by id
   */
  removePreset: (id: string) => Promise<void>;
}

export const DashboardContext = createContext<DashboardContextProps | undefined>(undefined!);

export function DashboardProvider({children}:{
  children: React.ReactNode
}){

  // state of available ingredients in the database
  const [ingredients, setIngredients] = useState<Ingredient[]>([]);
  // state of the ingredients retrieved from logged user's database
  const [ownedIngredients, setOwnedIngredients] = useState<OwnedIngredient[]>([]);

  // state for loading the owned ingredients
  const [isLoadingOwnedIngredients, setIsLoadingOwnedIngredients] = useState(false);

  // selected ingredient from UI to add to inventory
  const [selectedIngredientId, setSelectedIngredientId] = useState<string>("");

  // suggestion dialog
  const suggestionDialogRef = useRef<HTMLDialogElement | null>(null);

  // state for recipe suggestions
  const [suggestedRecipes, setSuggestedRecipes] = useState<Recipe[]>([]);

  // state for loading suggestion from AI
  const [isLoadingResponse, setIsLoadingResponse] = useState(false);

  // active dish type filter for recipe suggestions ("" = no filter)
  const [dishType, setDishType] = useState<DishType>("");

  // mirrors dishType so in-flight suggestion requests can detect filter changes
  const dishTypeRef = useRef<DishType>("");

  // active nutrient priority filter for recipe suggestions ("" = no priority)
  const [nutrientPriority, setNutrientPriority] = useState<NutrientPriority>("");

  // mirrors nutrientPriority so in-flight suggestion requests can detect filter changes
  const nutrientPriorityRef = useRef<NutrientPriority>("");

  // allow-suggested-ingredients flag for recipe suggestions (false = inventory only)
  const [allowSuggestedIngredients, setAllowSuggestedIngredients] = useState<boolean>(false);

  // mirrors allowSuggestedIngredients so in-flight suggestion requests can detect filter changes
  const allowSuggestedIngredientsRef = useRef<boolean>(false);

  // whether market mode (live suggestions while queueing) is enabled
  const [marketMode, setMarketMode] = useState(false);

  // mirrors marketMode so in-flight suggestion requests can detect toggles
  const marketModeRef = useRef<boolean>(false);

  // previous marketMode value so the effect can fire immediately on enable
  const wasMarketModeRef = useRef(false);

  // mirrors the queued ingredient ids so in-flight requests can detect queue changes
  const queuedIdsRef = useRef<string[]>([]);

  // stable handle to refreshRecommendedRecipes for the debounced market-mode effect
  const refreshRecommendedRecipesRef = useRef<() => Promise<void>>(refreshRecommendedRecipes);
  refreshRecommendedRecipesRef.current = refreshRecommendedRecipes;

  // id of the most recent suggestion request; older requests are stale
  const latestRequestIdRef = useRef(0);

  // id of the most recent instant-generation request; independent of the
  // dialog suggestion requests so the two cannot cancel each other
  const latestInstantRequestIdRef = useRef(0);

  /**
   * update the dish type filter and invalidate any in-flight suggestion request
   */
  function updateDishType(value: DishType){
    if (value === dishTypeRef.current){
      setDishType(value);
      return;
    }

    dishTypeRef.current = value;
    setDishType(value);

    invalidateInFlightSuggestions();
  }

  /**
   * update the nutrient priority filter and invalidate any in-flight suggestion request
   */
  function updateNutrientPriority(value: NutrientPriority){
    if (value === nutrientPriorityRef.current){
      setNutrientPriority(value);
      return;
    }

    nutrientPriorityRef.current = value;
    setNutrientPriority(value);

    invalidateInFlightSuggestions();
  }

  /**
   * update the allow-suggested-ingredients flag and invalidate any in-flight suggestion request
   */
  function updateAllowSuggestedIngredients(value: boolean){
    if (value === allowSuggestedIngredientsRef.current){
      setAllowSuggestedIngredients(value);
      return;
    }

    allowSuggestedIngredientsRef.current = value;
    setAllowSuggestedIngredients(value);

    invalidateInFlightSuggestions();
  }

  /**
   * toggle market mode and invalidate any in-flight suggestion request
   */
  function updateMarketMode(value: boolean){
    if (value === marketModeRef.current){
      setMarketMode(value);
      return;
    }

    marketModeRef.current = value;
    setMarketMode(value);

    invalidateInFlightSuggestions();
  }

  /**
   * invalidate any in-flight suggestion request for the old filters
   */
  function invalidateInFlightSuggestions(){
    latestRequestIdRef.current++;
    latestInstantRequestIdRef.current++;

    // no replacement request is running yet; stop the spinners here so a
    // discarded response cannot leave the dialog / instant generation
    // "thinking" forever
    setIsLoadingResponse(false);
    setIsGeneratingNow(false);
  }

  // state for loading while adding an ingredient
  const [isLoadingAddIngredient, setIsLoadingAddIngredient] = useState(false);

  // state to temporarily store ingredients that the user wants to add
  const [ ingredientsToAdd, setIngredientsToAdd ] = useState<inputOption[]>([]);

  // selected id of the owned ingredients, can be used to delete/edit multiple ingredients at the same time
  const [ selectedOwnedIngredientId, setSelectedOwnedIngredientId ] = useState<string[]>([]);

  // state to check if owned ingredients are currently being deleted
  const [ isDeletingOwnedIngredients, setIsDeletingOwnedIngredients ] = useState(false);

  // list of saved fridge presets
  const [presets, setPresets] = useState<Preset[]>([]);

  // loading state for fetching presets
  const [isLoadingPresets, setIsLoadingPresets] = useState(false);


  /**
   * reload the state for suggested recipes
   */
  async function refreshRecommendedRecipes(){
    // mark any prior in-flight request as superseded
    const requestId = ++latestRequestIdRef.current;

    try {
      setIsLoadingResponse(true);

      const requestedDishType = dishTypeRef.current;
      const requestedPriority = nutrientPriorityRef.current;
      const requestedAllowSuggested = allowSuggestedIngredientsRef.current;
      // in market mode the queued items count as prospective inventory
      const requestedQueuedIds = marketModeRef.current
        ? [...queuedIdsRef.current]
        : [];

      const filters: MealFilters = {};
      if (requestedDishType) filters.type = requestedDishType;
      if (requestedPriority) filters.nutrientPriority = requestedPriority;
      if (requestedAllowSuggested) filters.allowSuggestedIngredients = true;
      if (requestedQueuedIds.length > 0) filters.ingredientIds = requestedQueuedIds;
      const hasFilters = Boolean(
        requestedDishType ||
        requestedPriority ||
        requestedAllowSuggested ||
        requestedQueuedIds.length > 0
      );

      const data = await getRecommendedMeals(hasFilters ? filters : undefined);

      // a newer request is in flight; let it own the result and the loading state
      if (requestId !== latestRequestIdRef.current) return;
      // a filter changed while this request was pending; discard the stale result
      if (requestedDishType !== dishTypeRef.current) return;
      if (requestedPriority !== nutrientPriorityRef.current) return;
      if (requestedAllowSuggested !== allowSuggestedIngredientsRef.current) return;
      // the market-mode queue changed while this request was pending
      if (
        marketModeRef.current &&
        JSON.stringify(requestedQueuedIds) !== JSON.stringify(queuedIdsRef.current)
      ) return;

      setSuggestedRecipes(data!);
    } catch (error) {
      console.error(error);
    } finally {
      // keep the spinner running while a newer request is still pending
      if (requestId === latestRequestIdRef.current)
        setIsLoadingResponse(false);
    }
  } 

  // state for loading while instantly generating a single recipe
  const [isGeneratingNow, setIsGeneratingNow] = useState(false);

  /**
   * instantly generate a single recipe suggestion, respecting the active
   * filters, and return the first result (or null) for the caller to hand
   * off to the /recipe page. Does not mutate the suggestion list.
   */
  async function generateRecipeNow(): Promise<Recipe | null> {
    const requestId = ++latestInstantRequestIdRef.current;

    try {
      setIsGeneratingNow(true);

      const requestedDishType = dishTypeRef.current;
      const requestedPriority = nutrientPriorityRef.current;
      const requestedAllowSuggested = allowSuggestedIngredientsRef.current;
      // in market mode the queued items count as prospective inventory
      const requestedQueuedIds = marketModeRef.current
        ? [...queuedIdsRef.current]
        : [];

      const filters: MealFilters = {};
      if (requestedDishType) filters.type = requestedDishType;
      if (requestedPriority) filters.nutrientPriority = requestedPriority;
      if (requestedAllowSuggested) filters.allowSuggestedIngredients = true;
      if (requestedQueuedIds.length > 0) filters.ingredientIds = requestedQueuedIds;
      const hasFilters = Boolean(
        requestedDishType ||
        requestedPriority ||
        requestedAllowSuggested ||
        requestedQueuedIds.length > 0
      );

      const data = await getRecommendedMeals(hasFilters ? filters : undefined);

      // a newer instant-generation request is in flight; let it own the result
      if (requestId !== latestInstantRequestIdRef.current) return null;
      // a filter changed while this request was pending; discard the stale result
      if (requestedDishType !== dishTypeRef.current) return null;
      if (requestedPriority !== nutrientPriorityRef.current) return null;
      if (requestedAllowSuggested !== allowSuggestedIngredientsRef.current) return null;
      // the market-mode queue changed while this request was pending
      if (
        marketModeRef.current &&
        JSON.stringify(requestedQueuedIds) !== JSON.stringify(queuedIdsRef.current)
      ) return null;

      return data?.[0] ?? null;
    } catch (error) {
      console.error(error);
      return null;
    } finally {
      // keep the spinner running while a newer instant-generation request
      // is still pending; a filter-change invalidation clears it separately
      if (requestId === latestInstantRequestIdRef.current)
        setIsGeneratingNow(false);
    }
  }

  /**
   * market mode: regenerate suggestions live as the queue changes
   * (immediately on enable; ~500ms after each subsequent queue change)
   */
  useEffect(() => {
    const justEnabled = marketMode && !wasMarketModeRef.current;
    wasMarketModeRef.current = marketMode;

    if (!marketMode) return;

    queuedIdsRef.current = ingredientsToAdd.map((ingredient) => ingredient.value);

    const timer = setTimeout(() => refreshRecommendedRecipesRef.current(), justEnabled ? 0 : 500);
    return () => clearTimeout(timer);
  }, [marketMode, ingredientsToAdd, dishType, nutrientPriority, allowSuggestedIngredients]);

  /**
   * fetch the owned ingredients of logged user
   */
  async function fetchOwnedIngredients(){
    try {
      // update state for UI loading animation
      setIsLoadingOwnedIngredients(true);

      // fetch the owned ingredients
      const data = await getOwnedIngredients();
      setOwnedIngredients(data);
    } catch (error){
      console.error(error);
    } finally {
      setIsLoadingOwnedIngredients(false);
    }
  }
 
  /**
   * refresh the list of available ingredients
   */
  async function RefreshIngredientList(){
    const data = await getAllIngredients();
    setIngredients(data);
  }

  /**
   * fetch the user's saved presets
   */
  async function fetchPresets(){
    try {
      setIsLoadingPresets(true);
      const data = await getPresets();
      setPresets(data);
    } catch (error){
      console.error(error);
    } finally {
      setIsLoadingPresets(false);
    }
  }

  /**
   * save the user's current owned ingredients as a named preset
   */
  async function addPreset(name: string){
    const presetIngredients: PresetIngredient[] = ownedIngredients.map(oi => ({
      id: oi.ingredient.id,
      name: oi.ingredient.name,
      quantity: oi.quantity ?? undefined,
      expires_at: oi.expires_at ?? undefined,
    }));

    const saved = await savePreset(name, presetIngredients);
    setPresets(prev => {
      const existing = prev.findIndex(p => p.id === saved.id);
      if (existing >= 0) {
        const next = [...prev];
        next[existing] = saved;
        return next;
      }
      return [saved, ...prev];
    });
  }

  /**
   * populate ingredientsToAdd with a preset's ingredients
   */
  function applyPreset(preset: Preset){
    const mapped: inputOption[] = preset.ingredients.map(ing => ({
      label: ing.name,
      value: ing.id,
      quantity: ing.quantity,
      expires_at: ing.expires_at,
    }));
    setIngredientsToAdd(mapped);
  }

  /**
   * delete a preset by id
   */
  async function removePreset(id: string){
    await deletePreset(id);
    setPresets(prev => prev.filter(p => p.id !== id));
  }
  
  return (
    <DashboardContext.Provider value={{
      ingredients,
      setIngredients,
      ownedIngredients,
      setOwnedIngredients,
      isLoadingOwnedIngredients,
      setIsLoadingOwnedIngredients,
      selectedIngredientId,
      setSelectedIngredientId,
      suggestionDialogRef,
      suggestedRecipes,
      setSuggestedRecipes,
      isLoadingResponse,
      setIsLoadingResponse,
      dishType,
      setDishType: updateDishType,
      nutrientPriority,
      setNutrientPriority: updateNutrientPriority,
      allowSuggestedIngredients,
      setAllowSuggestedIngredients: updateAllowSuggestedIngredients,
      marketMode,
      setMarketMode: updateMarketMode,
      refreshRecommendedRecipes,
      generateRecipeNow,
      isGeneratingNow,
      setIsGeneratingNow,
      fetchOwnedIngredients,
      RefreshIngredientList,
      isLoadingAddIngredient,
      setIsLoadingAddIngredient,
      ingredientsToAdd,
      setIngredientsToAdd,
      selectedOwnedIngredientId,
      setSelectedOwnedIngredientId,
      isDeletingOwnedIngredients,
      setIsDeletingOwnedIngredients,
      presets,
      setPresets,
      isLoadingPresets,
      setIsLoadingPresets,
      fetchPresets,
      addPreset,
      applyPreset,
      removePreset
    }}>
      {children}
    </DashboardContext.Provider>
  );
}

export const useDashboardContext = () => useContext(DashboardContext);
