import { createContext, useContext, useState, useRef } from "react";
import {
  getOwnedIngredients,
  getAllIngredients,
} from "@/lib/services/Ingredients";

import { getRecommendedMeals } from '@/lib/services/Meal';

interface DashboardContextProps {
  /**
   * list of available ingredients for all users
   */
  ingredients: Ingredient[];
  setIngredients: (ingredients: Ingredient[]) => void;

  /**
   * list of ingredients owned by logged user
   */
  ownedIngredients: OwnedIngredient[];
  setOwnedIngredients: (ownedIngredients: OwnedIngredient[]) => void;

  /**
   * state for loading the owned ingredients
   */
  isLoadingOwnedIngredients: boolean;
  setIsLoadingOwnedIngredients: (isLoadingOwnedIngredients: boolean) => void;

  /**
   * selected ingredient from UI to add to inventory
   */
  selectedIngredientId: string;
  setSelectedIngredientId: (selectedIngredientId: string) => void;

  /**
   * suggestion dialog for displaying recipe suggestions from AI
   */
  suggestionDialogRef: React.RefObject<HTMLDialogElement | null>;

  /**
   * list of suggested recipes generated by AI
   */
  suggestedRecipes: Recipe[];
  setSuggestedRecipes: React.Dispatch<React.SetStateAction<Recipe[]>>;

  /**
   * state for loading suggestion from AI
   */
  isLoadingResponse: boolean;
  setIsLoadingResponse: (isLoadingResponse: boolean) => void;

  /**
   * refresh the content of suggestion dialog
   */
  refreshRecommendedRecipes: () => Promise<void>;

  /**
   * fetch the owned ingredients by the user
   */
  fetchOwnedIngredients: () => Promise<void>;

  /**
   * resets the list of available ingredients for all users
   */
  RefreshIngredientList: () => Promise<void>;

  /**
   * state for loading while adding an ingredient
   */
  isLoadingAddIngredient: boolean;
  setIsLoadingAddIngredient: (isLoadingAddIngredient: boolean) => void;
}

export const DashboardContext = createContext<DashboardContextProps | undefined>(undefined!);

export function DashboardProvider({children}:{
  children: React.ReactNode
}){

  // state of available ingredients in the database
  const [ingredients, setIngredients] = useState<Ingredient[]>([]);
  // state of the ingredients retrieved from logged user's database
  const [ownedIngredients, setOwnedIngredients] = useState<OwnedIngredient[]>([]);

  // state for loading the owned ingredients
  const [isLoadingOwnedIngredients, setIsLoadingOwnedIngredients] = useState(false);

  // selected ingredient from UI to add to inventory
  const [selectedIngredientId, setSelectedIngredientId] = useState<string>("");

  // suggestion dialog
  const suggestionDialogRef = useRef<HTMLDialogElement | null>(null);

  // state for recipe suggestions
  const [suggestedRecipes, setSuggestedRecipes] = useState<Recipe[]>([]);

  // state for loading suggestion from AI
  const [isLoadingResponse, setIsLoadingResponse] = useState(false);

  // state for loading while adding an ingredient
  const [isLoadingAddIngredient, setIsLoadingAddIngredient] = useState(false);


  /**
   * reload the state for suggested recipes
   */
  async function refreshRecommendedRecipes(){
    try {
      setIsLoadingResponse(true);
      const data = await getRecommendedMeals();
      setSuggestedRecipes(data!);  
    } catch (error) {
      console.error(error);
    } finally {
      setIsLoadingResponse(false);
    }
  } 

  /**
   * fetch the owned ingredients of logged user
   */
  async function fetchOwnedIngredients(){
    try {
      // update state for UI loading animation
      setIsLoadingOwnedIngredients(true);

      // fetch the owned ingredients
      const data = await getOwnedIngredients();
      setOwnedIngredients(data);
    } catch (error){
      console.error(error);
    } finally {
      setIsLoadingOwnedIngredients(false);
    }
  }
 
  /**
   * refresh the list of available ingredients
   */
  async function RefreshIngredientList(){
    const data = await getAllIngredients();
    setIngredients(data);
  }
  
  return (
    <DashboardContext.Provider value={{
      ingredients,
      setIngredients,
      ownedIngredients,
      setOwnedIngredients,
      isLoadingOwnedIngredients,
      setIsLoadingOwnedIngredients,
      selectedIngredientId,
      setSelectedIngredientId,
      suggestionDialogRef,
      suggestedRecipes,
      setSuggestedRecipes,
      isLoadingResponse,
      setIsLoadingResponse,
      refreshRecommendedRecipes,
      fetchOwnedIngredients,
      RefreshIngredientList,
      isLoadingAddIngredient,
      setIsLoadingAddIngredient
    }}>
      {children}
    </DashboardContext.Provider>
  );
}

export const useDashboardContext = () => useContext(DashboardContext);